format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$docker_context\
$time\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
format = '[$user > $hostname]($style)'
[directory]

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# "Important  " = "  "

[c]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[docker_context]
symbol = " "
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[elm]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[git_branch]
symbol = ""

[git_status]

[golang]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[haskell]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[julia]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nim]
symbol = " "
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
